const express = require('express')
const router = express.Router()
const authenticationRouter = require('./user.route')
const houseTypesRouter = require('./house_types.route')
const favouriteStylesRouter = require('./favourite_styles.route')
const blogsRouter = require('./blogs.route')
const videosRouter = require('./videos.route')
const enquiryRouter = require('./enquiry.route')
const s3Router = require('./s3.route')
const advertisementRouter = require('./advertisements.route')
const inspirationRouter = require('./inspirations.route')
const trendingRouter = require('./trending.route')
const designsRouter = require('./designs.route')
const propertyTypesRouter = require('./property_types.route')
const trendingTypesRouter = require('./trending_types.route')

router.use("/auth", authenticationRouter)
router.use("/house-types", houseTypesRouter)
router.use("/favourite-styles", favouriteStylesRouter)
router.use("/blogs", blogsRouter)
router.use("/videos", videosRouter)
router.use('/enquiry', enquiryRouter)
router.use('/s3', s3Router)
router.use('/advertisements', advertisementRouter)
router.use('/inspirations', inspirationRouter)
router.use('/trendings', trendingRouter)
router.use('/designs', designsRouter)
router.use("/property-types", propertyTypesRouter)
router.use("/trending-types", trendingTypesRouter)


module.exports = router;